name: Post coverage comment

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

jobs:
  report-coverage:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'

    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write

      # Gives the action the necessary permissions for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write

      # Gives the action the necessary permissions for looking up the
      # workflow that launched this workflow, and download the related
      # artifact that contains the comment to be published
      actions: read

    steps:
      - uses: actions/checkout@v4 # See [DANGER] above.

      - name: Download code coverage data
        uses: actions/download-artifact@v4
        with: { name: code-coverage-data }

      - name: Create code coverage comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERAGE_DATA_BRANCH: coverage-data
